### PR TITLE
Ui design

### PR DESCRIPTION
**Pull request by wesv**

### CODE REVIEW

**Comment by kyl1394** [comment]
Would it be possible to make the whole window scaled down in size a little bit when it first opens? It is kind of cut off with my weird resolution so it'd be better if it started smaller and then you could maximize it. If it's not super easy to do that then don't worry.

**Comment by kyl1394** [comment]
Also kind of odd that it changes it's window size when you initially upload an image. Any way to change that so that it just stays a constant size?

**Comment by kyl1394** [comment]
After those fixes then +1 & merge

**Comment by wesv** [comment]
All we have to do is modify the size of the initial load up is to change the dimensions of UnselectedImg.png. Super easy.

**Pull request merged**
